export const DIE_SIZE = 120;

export const ANIMATION_DELAY = 250;
export const ANIMATION_ITERATIONS = 3;
export const ANIMATION_DURATION = 3000;

export const ROLL_DURATION = ANIMATION_DURATION + ANIMATION_DELAY * 2;
